"""001_initial_schema

Revision ID: 706d67d99754
Revises:
Create Date: 2026-08-21 22:38:14.343701

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "706d67d99754"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
