[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tesseractcli"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "rich>=13.0.0",
    "textual<=8.2.7"
]

[project.scripts]
tesseract = "tesseractcli.cli.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/tesseractcli"]